### ISSUE TITLE
Is it possible to input data without determining top_level beforehand.

### ISSUE THREAD

**Issue by chross** [CCGE-BOADICEA/pedigreejs#104]
Hi!
I want to know if I can input tabular data that has no tree structure and let pedigreejs do the tree building. I know this is possible for BOADICEA and PED files, but this function would be incredibly useful for the regular data format.

**Comment by tcarver** [comment]
Hi, I am not sure what you mean by regular data format? BOADICEA is tabular format.

**Comment by tcarver** [comment]
Closing for now but please reopen if you have an example file.
