### ISSUE TITLE
Export to PED?

### ISSUE THREAD

**Issue by taspapak** [CCGE-BOADICEA/pedigreejs#105]
Hello,

Is it possible to export the Pegidree in PED format? I was thinking to parse the JSON and generate a PED from there but I wondered if there is an easier way to do this?

Thanks,
Tasos

**Comment by taspapak** [comment]
Hi @tcarver , 

That's the plan, to integrate it in an interface and I am currently working on it.Would be nice to know that we make this export.

Cheers,
Tasos

**Comment by tcarver** [comment]
That's sound good @taspapak. Best wishes for the integration.
Tim
