### ISSUE TITLE
Wrong symbol for miscarriage/termination of unknown 

### ISSUE THREAD

**Issue by desaurabh** [CCGE-BOADICEA/pedigreejs#107]
- **To reproduce -**
  I have added a new sibling and marked its gender as 'unknown' and then in the reproduction, i selected termination or miscarriage.
- **Expected result -** 
  Ideally, the node should be drawn as equilateral triangle but in the given scenario it is getting tilted to one side.

**Comment by desaurabh** [comment]
Reference line [code](https://github.com/CCGE-BOADICEA/pedigreejs/blob/0dc02b35a41ec190f1998c6d63a3302cea59c785/js/pedigree.js#L647) that causing it. Not sure if that is required on purpose.

**Comment by tcarver** [comment]
Thanks. A fix has been applied in this [commit](https://github.com/CCGE-BOADICEA/pedigreejs/commit/d1267991f5fb990e6e4da990850b20c9740db9c8).
