### ISSUE TITLE
Disesses list color mapping mapping 

### ISSUE THREAD

**Issue by VivithaAlamur** [CCGE-BOADICEA/pedigreejs#119]
Hi, 

We are using pedigree js for our development.As per our requirement we can map multiple diseases to the patient.

We are having our own set of diseases list along with mapping code.

Can you please let us know how to map our diseases to the pedigree tree with our own color codes for each diseases.

Regards
vivitha

**Comment by tcarver** [comment]
@VivithaAlamur please take a look at this example https://ccge-boadicea.github.io/pedigreejs/docs/example1.html
