### ISSUE TITLE
Start pedigree with two nodes.

### ISSUE THREAD

**Issue by pyshawon** [CCGE-BOADICEA/pedigreejs#120]
Hello developers,
I'm developing a pedigree with a lot of features. I'm using **pedigreejs** as a base of my pedigree.
Right now in **pedigreejs**  you can create nodes on top of a child node. [Example Image](https://i.ibb.co/Hz17gdR/Screenshot.png). I mean right now we are starting pedigree with three nodes one child and parents and if you delete child node parents got separated. 

But is there any way to create or start a pedigree without a chile node there will be only couple? [Like this image](https://i.ibb.co/XSDcYmJ/Screenshot-1.png). I want to start pedigree with two nodes(Like, a couple without a child at the beginning of pedigree). 

Thank You.

**Comment by tcarver** [comment]
Hi @pyshawon, no there is currently no way of doing this and we currently have no plans to implement. regards
