### ISSUE TITLE
Life Status radio button

### ISSUE THREAD

**Issue by desaurabh** [CCGE-BOADICEA/pedigreejs#121]
Life Status radio buttons are not getting updated after reopening the dialog. (values are getting updated just fine)

Reference line [code](https://github.com/CCGE-BOADICEA/pedigreejs/blob/97b2f46e9b5c1c8c7ad012789da0d1f2ac1b1cfa/js/widgets.js#L428). 
Most likely the issue is with the conditional statement that tries to compare string value with an integer value type.

**Comment by tcarver** [comment]
Thanks @desaurabh. Latest commit should help.
