### ISSUE TITLE
Some pedigrees don't have an optimal display

### ISSUE THREAD

**Issue by chross** [CCGE-BOADICEA/pedigreejs#144]
I have some pedigrees which will display poorly in terms of layout. Often, persons on one level are suboptimally arranged in a way that connecting lines are either very long or have a lot of crossings.

I can provide examples as both image and BOADICEA2.0 format files.

**Comment by chross** [comment]
Here is an example pedigree and corresponding boadicea2.0 file

![plot](https://github.com/CCGE-BOADICEA/pedigreejs/assets/7794409/fe9a3066-9145-4d51-8b96-8cb0b726bc03)

[23748019.txt](https://github.com/CCGE-BOADICEA/pedigreejs/files/14373871/23748019.txt)

**Comment by tcarver** [comment]
@chross you can now SHIFT and drag the grandparents to achieve a better layout:

![image](https://github.com/user-attachments/assets/310c9b71-8c63-40ca-9b2c-a96c39415e4a)
