### ISSUE TITLE
Save / load errors?

### ISSUE THREAD

**Issue by shanemuk** [CCGE-BOADICEA/pedigreejs#146]
Some pedigrees when you Save and then Load, you lose the top level parents. Then if you save that pedigree and load it again, they reappear! Repeat ad infinitum... 
[ped (12).txt](https://github.com/CCGE-BOADICEA/pedigreejs/files/10157855/ped.12.txt)
[ped (11).txt](https://github.com/CCGE-BOADICEA/pedigreejs/files/10157856/ped.11.txt)
see these two files - they should display the same pedigree; 12 is the saved product of 11, but the saved product of 12 reverts to 11. 12 opens properly displaying the top level individuals, 11 doesn't...
Thanks for checking!

**Comment by tcarver** [comment]
This format (JSON) is not used for our save/load requirements, so thanks for reporting it. This has been fixed now.
