### ISSUE TITLE
How do I include pedigreejs in a modern React project?

### ISSUE THREAD

**Issue by Julian-Tipler** [CCGE-BOADICEA/pedigreejs#149]
Apologies, new dev here. I was wondering how to install this library for use inside of a dangerouslysetinnerhtml tag of a React project.

I didn't see any instructions for installing this library. How do others include this library in projects, React based or even vanilla javascript based?

Thanks so much for your work on this project. The Sciences are incredibly important to me (working on an orca whale pedigree project for a friend) and I appreciate you providing a free version to use.

**Comment by tcarver** [comment]
@Julian-Tipler probably a bit late but there is now a pedigreejs React App example:

https://ccge-boadicea.github.io/pedigreejs-react-app/
