### ISSUE TITLE
Adding/deleting parents causes display issue

### ISSUE THREAD

**Issue by ryan-hdez** [CCGE-BOADICEA/pedigreejs#158]
Hi,

I’ve found a reproducible bug that occurs when starting w/ the initial, 3-person pedigree (mother, father, child). The issue generally occurs as follows:

* add parents for someone in second generation
* remove newly added set of parents
* add another set of parents for anyone in second generation

If a partner (for someone in the second generation) was added before Bullet 1 or between Bullets 1 & 2, the pedigree display scrambles, and the newly added partner is incorrectly shown to be consanguineous.

An example case would be if we added parents for “father” [paternal grandparents], added a new partner for “mother”, deleted the parents for “father” [paternal grandparents], then added parents for “mother” [maternal grandparents].

Any idea why this might be happening? Thanks!

~~
@daniellebraun

**Comment by tcarver** [comment]
Thanks @daniellebraun 
Please see the fix
