### ISSUE TITLE
Moving nods and automatic rearangments

### ISSUE THREAD

**Issue by aardes** [CCGE-BOADICEA/pedigreejs#163]
Dear,

I am wondering if would it be possible to allow the nodes to move. to rearrange the items its better to allow the user to move the nodes. 

here is an example:

![plot (1)](https://github.com/CCGE-BOADICEA/pedigreejs/assets/12953535/73250c8e-87c5-46d3-a2e8-4d0f780cf9d7)

thanks

**Comment by AkshayTripathiShorthillsAI** [comment]
Exactly more complex pedigree trees are not clearly showing relations , and the diagram is not looking good , draggable nodes will be a fantastic feature to pedigree js

**Comment by tcarver** [comment]
@aardes @AkshayTripathiShorthillsAI  it's now possible to SHIFT and select a node to drag a node
