### ISSUE TITLE
Bug example 3 - changes in the form not applied to the pedigree

### ISSUE THREAD

**Issue by kat-leen** [CCGE-BOADICEA/pedigreejs#165]
Hello!

Thank you for the library! It is very useful.

I noticed a bug in the third example. The changes in the form are not applied to the pedigree (see screenshot) and we cannot modify the original fields anymore (age, name, etc.).
Error : "Uncaught ReferenceError: pedigree_form is not defined"

![image](https://github.com/CCGE-BOADICEA/pedigreejs/assets/9191279/65fd846f-0b1a-4f98-903a-252fcdee9a69)

Thank you

**Comment by tcarver** [comment]
Thanks @kat-leen that is fixed now
