### ISSUE TITLE
Lot of errors converting to Javascript

### ISSUE THREAD

**Issue by GantaVenkataKousik** [CCGE-BOADICEA/pedigreejs#173]
This was not suitable for most use cases as it could not be converted to JavaScript.  
If anyone has successfully done so, please share the link with me.

**Comment by tcarver** [comment]
@GantaVenkataKousik have you tried the JavaScript in the build directory?

**Comment by GantaVenkataKousik** [comment]
> @GantaVenkataKousik have you tried the JavaScript in the build directory?

yes, would you like to have a look at the repo
that will be greatly helpful

**Comment by tcarver** [comment]
@GantaVenkataKousik have you tried creating the pedigreejs ES bundle and using that: 

npm run build-es

? Also, we have a React example now that hopefully helps to see what you need:

https://ccge-boadicea.github.io/pedigreejs-react-app/

https://github.com/CCGE-BOADICEA/pedigreejs-react-app/blob/master/src/PedigreeJS.jsx

**Comment by GantaVenkataKousik** [comment]
Thank you so much for letting me know about this 
will this try out
