### ISSUE TITLE
Crossing generations?

### ISSUE THREAD

**Issue by anderspitman** [CCGE-BOADICEA/pedigreejs#84]
Hey @tcarver, does pedigreejs currently have any functionality for handling crossing generations (ie an individual has a child with their aunt/uncle, etc)? It doesn't appear like it from reading the paper and website, but figured I'd ask. Looking for something similar to what kinship2 and cranefoot do, but in JavaScript.

**Comment by tcarver** [comment]
@anderspitman currently no it will only create the relationship at the same level in the family tree, https://ccge-boadicea.github.io/pedigreejs/docs/example5.html

**Comment by tcarver** [comment]
Hi @anderspitman support has been added now, please see
https://ccge-boadicea.github.io/pedigreejs/docs/example9.html

**Comment by anderspitman** [comment]
Awesome, thanks!
