### ISSUE TITLE
Error: not unique child

### ISSUE THREAD

**Issue by chross** [CCGE-BOADICEA/pedigreejs#90]
When adding a sibling to a child from a father->daughter relationship, non unique ids are produced and the pedigree failes to render.

Tested using current dist from 24 d ago.

To reproduce do:

In initial Father, Mother, Child (F) configuration, add a relationship between father and daughter. Besides the display problems that now both child generation linking lines will be on the exact same level, try to add a sibling to the child of this relationship. Pedigree construction will be aborted.

![image](https://user-images.githubusercontent.com/7794409/56894361-e8c61100-6a85-11e9-80a1-2e6525f45d28.png)

**Comment by tcarver** [comment]
Many thanks for raising this issue. A fix has been applied for this and is now available.
